module.exports = [
  {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com/',
    inputSelector: 'textarea#chat-input, textarea', 
    buttonSelector: null, 
    submitType: 'enter',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"]', // 消息容器选择器
  },
  {
    name: '通义千问 (Qwen)',
    url: 'https://tongyi.aliyun.com/qianwen/',
    inputSelector: 'textarea',
    buttonSelector: 'button[class*="ant-btn"]', 
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="conversation"]',
  },
  {
    name: 'Kimi (Moonshot)',
    url: 'https://kimi.moonshot.cn/',
    inputSelector: 'div[contenteditable="true"]', 
    buttonSelector: 'div[class*="sendButton"], button[class*="sendButton"]', 
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
  },
  {
    name: '字节豆包',
    url: 'https://www.doubao.com/',
    inputSelector: 'div[contenteditable="true"], textarea',
    buttonSelector: 'button[class*="send-btn"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
  },
  {
    name: '文心一言',
    url: 'https://yiyan.baidu.com/',
    // 简化选择器，优先匹配 ID
    inputSelector: '#erp-text-input, div.yc-editor, div[contenteditable="true"]', 
    buttonSelector: 'div[class*="send-btn"], button[class*="send"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="content"]',
  },
  {
    name: '腾讯元宝',
    url: 'https://yuanbao.tencent.com/',
    inputSelector: 'div[contenteditable="true"]',
    buttonSelector: 'div[class*="send-btn"], button[class*="send"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
  },
  {
    name: '知乎直答',
    url: 'https://zhida.zhihu.com/',
    inputSelector: 'textarea, div[contenteditable="true"]',
    buttonSelector: null,
    submitType: 'enter',
    messageSelector: '[class*="message"], [class*="Message"], [class*="answer"], [class*="content"]',
  },
  {
    name: 'Google Gemini (需科学上网)',
    url: 'https://gemini.google.com/',
    inputSelector: 'div[contenteditable="true"]',
    buttonSelector: 'button[class*="send-button"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="model-response"]',
  },
  {
    name: 'ChatGPT (需科学上网)',
    url: 'https://chatgpt.com/',
    inputSelector: '#prompt-textarea',
    buttonSelector: 'button[data-testid="send-button"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [data-message-author-role="assistant"]',
  },
  {
    name: 'Claude (需科学上网)',
    url: 'https://claude.ai/',
    inputSelector: 'div[contenteditable="true"], textarea',
    buttonSelector: 'button[aria-label="Send Message"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="response"]',
  },
  {
    name: 'Grok (需科学上网)',
    url: 'https://grok.com/',
    inputSelector: 'textarea, div[contenteditable="true"]',
    buttonSelector: 'button[type="submit"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="response"]',
  },
  {
    name: 'MiniMax 海螺',
    url: 'https://agent.minimaxi.com/',
    inputSelector: 'textarea, div[contenteditable="true"]',
    buttonSelector: 'button[class*="send"]',
    submitType: 'click',
    messageSelector: '[class*="message"], [class*="Message"], [class*="bubble"]',
  }
];
